//
//  WeatherModels.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 24.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Weather
{
  // MARK: Use cases
  
  enum Get
  {
    struct Request
    {
        var city: String
    }
    struct Response
    {
        var item: WeatherResponse
    }
    struct ViewModel
    {
        struct Weather: Decodable {
            var city: String
            var temperature: String
            var cloudiness: String
            var description: String
            var windSpeed: String
        }
        var weather: Weather
    }
  }
}
