//
//  WeatherPresenter.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 24.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherPresentationLogic
{
  func presentWeather(response: Weather.Get.Response)
}

class WeatherPresenter: WeatherPresentationLogic
{
  weak var viewController: WeatherDisplayLogic?
  
  // MARK: Do something
  
  func presentWeather(response: Weather.Get.Response)
  {

   let wResponse  = response.item
        let spped = "\(wResponse.windSpeed)"
        let temp = "\(wResponse.temperature)º C"
        let model = Weather.Get.ViewModel.Weather(city: wResponse.city, temperature: temp, cloudiness: wResponse.cloudiness, description: wResponse.description, windSpeed: spped)
        let viewModel = Weather.Get.ViewModel(weather: model)
    viewController?.displayWeather(viewModel: viewModel)
  }
}
