//
//  FlightModels.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 24.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Flight
{
  // MARK: Use cases
  
  enum List
  {
    struct Request
    {
        var source: String
    }
    struct Response
    {
        var flights: [FlightResponse]
    }
    struct ViewModel
    {
        struct Flight {
            var destination: String
            var airline: String
            var price: String
            var transfers: String
        }
        
        var flights: [Flight]
    }
  }
    
    enum GetCity
    {
      struct Request
      {
          var index: Int
      }
      struct Response
      {
          var city: String
      }
      struct ViewModel
      {
        var city: String
      }
    }
}
