//
//  FlightWorker.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 24.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FlightWorker
{
    var flightApi: FlightAPIProtocol = FlightAPI()
    
  func fetch(city: String, completion: @escaping ([FlightResponse]) -> Void)
  {
    flightApi.fetch(city: city) { (result: Result<[FlightResponse], Error>) in
        switch result {
        case .success(let data):
            completion(data)
        case .failure(let error):
            print(error)
            completion([])
        }
    }
  }
}
