//
//  CityListPresenter.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 22.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListPresentationLogic
{
  func presentSomething(response: CityList.Something.Response)
}

class CityListPresenter: CityListPresentationLogic
{
  weak var viewController: CityListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CityList.Something.Response)
  {
    let viewModel = CityList.Something.ViewModel(items: response.items)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
