//
//  CityListInteractor.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 22.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListBusinessLogic
{
    var name: String { get set }
  func doSomething(request: CityList.Something.Request)
}

protocol CityListDataStore
{
  var name: String { get set }
}

class CityListInteractor: CityListBusinessLogic, CityListDataStore
{
  var presenter: CityListPresentationLogic?
  var worker: CityWorker = CityWorker(filename: "cities")
  var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CityList.Something.Request)
  {
    let response = CityList.Something.Response(items: worker.cities)
    presenter?.presentSomething(response: response)
  }
}
