//
//  ContainerInteractor.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 24.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContainerBusinessLogic
{
  func doSomething(request: Container.Something.Request)
}

protocol ContainerDataStore
{
  //var name: String { get set }
}

class ContainerInteractor: ContainerBusinessLogic, ContainerDataStore
{
  var presenter: ContainerPresentationLogic?
  var worker: ContainerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Container.Something.Request)
  {
    worker = ContainerWorker()
    worker?.doSomeWork()
    
    let response = Container.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
