//
//  ContainerPresenter.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 24.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContainerPresentationLogic
{
  func presentSomething(response: Container.Something.Response)
}

class ContainerPresenter: ContainerPresentationLogic
{
  weak var viewController: ContainerDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Container.Something.Response)
  {
    let viewModel = Container.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
