//
//  CityWorker.swift
//  CleanTest
//
//  Created by Vadim Yushchenko on 25.11.2019.
//  Copyright (c) 2019 Vadim Yushchenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct City: Decodable {
    var name: String
    var code: String
//    var countryCode: String
}

class CityWorker
{
    private var cities: [City] = []
    
    init(filename: String) {
        let url = Bundle.main.url(forResource: filename, withExtension: "json")!
        do {
            let jsonData = try Data(contentsOf: url)
            let decoder = JSONDecoder()
            cities = try decoder.decode([City].self, from: jsonData)

        } catch { print(error) }
    }
    
    subscript(code: String) -> String? {
        let city = cities.first(where: {$0.code == code})
        return city?.name
    }
}
